version: '3.7'

services:
  best4cast-api:
    container_name: best4cast-api
    build: ./
    working_dir: /usr/src/best4cast-api
    volumes: 
      - ./:/usr/src/best4cast-api
    environment:
      POSTGRES_URI: postgres://ser:ser@postgres:5432/best4cast-api-docker
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"
    command: npm start
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: ser
      POSTGRES_PASSWORD: ser
      POSTGRES_DB: best4cast-api-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"